import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

import "@/app/globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scrollbar-thin scrollbar-track-secondary scrollbar-thumb-primary overflow-x-hidden" suppressHydrationWarning={true} lang="es">
      <body className={`${cn("bg-background !m-0 overflow-x-hidden w-full max-w-full", inter.className)}`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
