import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/app/globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="es">
      <body className={`${cn("bg-background", inter.className)}`}>{children}</body>
    </html>
  );
}
