import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import LandingProviders from "@/modules/landing/presentation/providers/landing-providers/landing-providers";
import LandingSection from "@/modules/landing/presentation/components/shared/landing-section/landing-section";
import LandingNavbar from "@/modules/landing/presentation/components/shared/navbar/landing-navbar";
import LandingFooter from "@/modules/landing/presentation/components/shared/footer/footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Creativo",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LandingProviders>
      <Script id="landing-analitycs-link" async src={`https://www.googletagmanager.com/gtag/js?id=${process?.env?.ANALYTICS_LANDING}`}></Script>
      <Script
        id="landing-analitycs-link-2"
        dangerouslySetInnerHTML={{
          __html: `
<script async src="https://www.googletagmanager.com/gtag/js?id=${process?.env?.ANALYTICS_LANDING}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '${process?.env?.ANALYTICS_LANDING}');
</script>`,
        }}
      ></Script>
      <main suppressHydrationWarning={true} className="md:gap-y-0 flex flex-col">
        <LandingSection id="nav" className="fixed top-0 z-[50] bg-background">
          <LandingNavbar />
        </LandingSection>
        {children}
        <LandingSection className="mt-24">
          <LandingFooter />
        </LandingSection>
      </main>
    </LandingProviders>
  );
}
